### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by angMaidt** [Dave89rr/GameVault#1]
### Create a route handler for a request with path '/users/signup' and method of GET to display a sign up form.

- [x]  The route handler should render a sign-up form
- [x]  Should use csrfProtection and pass a csrf token to the pug template

### Create a pug template with a form to sign up a user

- [x] Form should apply csrfToken
- [x] Form should have required input fields name, email, password and confirm password
- [x] Form should submit to POST '/users/signup'

### Create a route handler to take in the form request with a path of '/users/signup' and a method of POST

- [x] Validate form data
- [x]  Re-render the form in the event of a validation check failure
- [x]  If there are no errors, create a new user and redirect the client to '/'

**Comment by Dave89rr** [comment]
Finished with commit [5fd8c40](https://github.com/Dave89rr/GameVault/commit/5fd8c40527290ef06185cf5ad01de4949b4e1ee4)
