### ISSUE TITLE
D3 bugs

### ISSUE THREAD

**Issue by anailopez** [Dave89rr/GameVault#18]
- [x] cannot render collection page when trying collections/:id (fixed in https://github.com/Dave89rr/GameVault/commit/08f5cb85a1111b5afab930595ab3ff1b076b3fbe)

Frontend Bugs
- [x]  new collection button on vault page doesn't redirect:
- [x] banner not displaying at 100% when screen minimized

**Comment by Dave89rr** [comment]
New Collection button on vault page has been fixed
