### ISSUE TITLE
Home Page with Log Out Button

### ISSUE THREAD

**Issue by angMaidt** [Dave89rr/GameVault#3]
### Create a route handler for a request with path '/' and method of GET to display a home page with a logout button.
- [x] The route handler should render homepage with a logout button
- [x]  Implement express-session package as middleware
- [x] Implement a logout function

### Create a pug template for homepage
- [ ] Page should have a navbar with logout button

**Comment by jiaqicheng1998** [comment]
c34fdcf8bd07d38aa1b90ed33e86a5e87153f43f
